from sqlalchemy import Column, Date, Numeric, String
from app.database import Base


class Property(Base):
    __tablename__ = "properties"

    geoid = Column(String(20), primary_key=True)
    source_geoid = Column(String(20), nullable=True)
    common_code = Column(String(20), nullable=True)
    old_common_code = Column(String(20), nullable=True)
    project_code = Column(String(20), nullable=True)
    sb_phase = Column(String(20), nullable=True)
    sb_survey = Column(String(20), nullable=True)
    sb_block = Column(String(20), nullable=True)
    sb_lot = Column(String(20), nullable=True)
    disposition_status = Column(String(1), nullable=True)
    property_type = Column(String(3), nullable=True)
    lhc = Column(String(1), nullable=True)
    development_status = Column(String(1), nullable=True)
    area_sqm = Column(Numeric(15, 2), nullable=True)
    tct_no = Column(String(20), nullable=True)
    tct_date = Column(Date, nullable=True)
    price_sqm = Column(Numeric(8, 2), nullable=True)
    program_class = Column(Numeric(5, 2), nullable=True)
    mode_disposition = Column(String(1), nullable=True)
    disposition_date = Column(Date, nullable=True)
    disposition_target = Column(String(1), nullable=True)
    transaction_type = Column(String(1), nullable=True)
    transaction_date = Column(Date, nullable=True)
    sales_report_no = Column(String(21), nullable=True)
    sales_report_date = Column(Date, nullable=True)
    effectivity_date = Column(Date, nullable=True)
    production_date = Column(Date, nullable=True)
    old_area = Column(Numeric(15, 2), nullable=True)
    emd_tag = Column(String(1), nullable=True)
    principal_amount = Column(Numeric(14, 2), nullable=True)
    house_interest_rate = Column(Numeric(5, 2), nullable=True)
    house_area_sqm = Column(Numeric(10, 2), nullable=True)
    house_price = Column(Numeric(10, 2), nullable=True)
    house_model = Column(String(10), nullable=True)
    house_downpayment = Column(Numeric(10, 2), nullable=True)
    house_terms = Column(Numeric(5, 2), nullable=True)
    house_amortization = Column(Numeric(10, 2), nullable=True)
    house_input_date = Column(Date, nullable=True)
    fvac_occ = Column(String(3), nullable=True)
    indicator = Column(String(1), nullable=True)
    inp_date = Column(Date, nullable=True)
    ntag = Column(String(3), nullable=True)
    active_stat = Column(String(3), nullable=True)
